version: '2'

services:
  postgres:
    restart: always
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - /opt/data/psql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=irremote
  nginx:
    restart: always
    image: nginx:1.19
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ir_remote.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
  web:
    restart: always
    build: ./web
    ports:
      - "8000:8000"
    volumes:
      - /usr/src/app/web/project/static
    command: flask run --host=0.0.0.0 --port 8000
    environment:
      - FLASK_ENV=development
    depends_on:
      - postgres